import React from 'react';
import PageContainer from 'components/containers/pageContainer/PageContainer';

export class HomePage extends React.Component {
  render() {
    return (
      <PageContainer>
        <div>HomePzzzzzzzzzage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePage</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePaged</div>
        <div>HomePagezxvxcvcxd</div>
      </PageContainer>
    );
  }
}

export default HomePage;
